fixed things caused by gobject stupidness (see https://bugzilla.gnome.org/show_bug.cgi?id=641944 )
Fixes this exception:

Traceback (most recent call last):
  File "/home/forrest/.local/share/gedit/plugins/autotab.py", line 54, in do_activate
    self.window.set_data("AutoTabPluginHandlerId", tab_added_id)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GObject.py", line 555, in _unsupported_data_method
    raise RuntimeError('Data access methods are unsupported. '
RuntimeError: Data access methods are unsupported. Use normal Python attributes instead
Traceback (most recent call last):
  File "/home/forrest/.local/share/gedit/plugins/autotab.py", line 53, in <lambda>
    tab_added_id = self.window.connect("tab_added", lambda w, t: self.connect_handlers(t.get_view()))
  File "/home/forrest/.local/share/gedit/plugins/autotab.py", line 79, in connect_handlers
    doc.set_data("AutoTabPluginHandlerIds", (loaded_id, saved_id))
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GObject.py", line 555, in _unsupported_data_method
    raise RuntimeError('Data access methods are unsupported. '
RuntimeError: Data access methods are unsupported. Use normal Python attributes instead